### ISSUE TITLE
SecretColumnSqlFilter supports URI

### ISSUE THREAD

**Issue by ymaegawa** [future-architect/uroborosql#118]
SecretColumnSqlFilter now supports only local file system.

https://github.com/future-architect/uroborosql/blob/2a0b79b624303c9ca52bc884154690050001c953/src/main/java/jp/co/future/uroborosql/filter/SecretColumnSqlFilter.java#L100

I want use URI like `https://~`.

**Comment by HidekiSugimoto189** [comment]
fixed by #121
