### ISSUE TITLE
When the result is null, have you assigned 0 to Integer?

### ISSUE THREAD

**Issue by hizuki-aizawa** [future-architect/uroborosql#133]
When the result is null, have you assigned 0 to Integer?
If the result is null if possible, please assign null to Integer.

I used `SqlAgent.query().param().collect()`

The way I am thinking fix, it is as follows.

PropertyMapperManager.class

Before
```java
	if (Integer.class.equals(rawType) || int.class.equals(rawType)) {
		return rs.getInt(columnIndex);
	}
```

After
```java
        if (Integer.class.equals(rawType)) {
            int result = rs.getInt(columnIndex);
            if (rs.wasNull()) {
                return null;
            }
            return result;
        }
        if (int.class.equals(rawType)) {
            return rs.getInt(columnIndex);
        }
```

**Comment by shout-star** [comment]
Thank you for suggestion.

Certainly in the current PropertyMapperManager implementation, if the type of the property of the Entity is a wrapper type, it will be filled with the primitive initial value returned by `ResultSet#getXXX`, and I think that there are cases where it is unintended behavior.

I'd like to fix it with the next version.
