### ISSUE TITLE
Add method of extraction condition in SqlEntityQuery

### ISSUE THREAD

**Issue by shout-star** [future-architect/uroborosql#152]
Since SqlEntityQuery only supports equality of extraction conditions, why not add the following support?

| method                                                                    | generated sql                    | comment                          |
|---------------------------------------------------------------------------|----------------------------------|----------------------------------|
| paramNotEqual("col", "value")                                             | col != 'value' or col <> 'value' | Do you support both operators?   |
| paramIn("col", "val1", "val2") paramInList("col", List.of("val1", "val2") | col in ('val1', 'val2')          | Is the method overloaded?        |
| paramLike("col", "%val%")                                                 | col like '%val%'                 | Do you want '%' to autocomplete? |
| paramBetween("col", 1, 2)                                                 | col between 1 and 2              |                                  |
| paramIsNull("col")                                                        | col is null                      |                                  |
| paramIsNotNull("col")                                                     | col is not null                  |                                  |
| paramGreaterThan("col", 1)                                                | col > 1                          |                                  |
| paramLessThan("col", 1)                                                   | col < 1                          |                                  |
| paramGreaterEqual("col", 1)                                               | col >= 1                         |                                  |
| paramLessEqual("col", 1)                                                  | col <= 1                         |                                  |
| paramRaw("col = 1 or col = 2")                                            | (col = 1 or col = 2)             |                                  |
| orderByAsc("col1", "col2")                                                | order by col1, col2 asc          | Do you support null first?       |
| orderByDesc("col1", "col2")                                               | order by col1, cols desc         |                                  |
| offset(10)                                                                | offset 10                        |                                  |
| limit(10)                                                                 | limit 10                         |                                  |

**Comment by HidekiSugimoto189** [comment]
The following extraction conditions are supported.

|method|generated sql|comment|
|:-------|:---------------|:-------------|
|equal("col", "value")|col = 'value'||
|notEqual("col", "value")|col != 'value'||
|greaterThan("col", 1)|col > 1||
|lessThan("col", 1)|col < 1||
|greaterEqual("col", 1)|col >= 1||
|lessThan("col", 1)|col <= 1||
|in("col", "val1", "val2")|col in ('val1', 'val2')||
|in("col", List.of("val1", "val2"))|col in ('val1', 'val2')||
|notIn("col", "val1", "val2")|col not in ('val1', 'val2')||
|notIn("col", List.of("val1", "val2"))|col not in ('val1', 'val2')||
|like("col", "%val%")|like '%val%'|"%val%" does not escape|
|startsWith("col", "val")|like 'val%'|"val" does escape|
|endsWith("col", "val")|like '%val'|"val" does escape|
|contains("col", "val")|like '%val%'|"val" does escape|
|notLike("col", "%val%")|not like '%val%'|"%val%" does not escape|
|notStartsWith("col", "val")|not like 'val%'|"val" does escape|
|notEndsWith("col", "val")|not like '%val'|"val" does escape|
|notContains("col", "val")|not like '%val%'|"val" does escape|
|between("col", 1, 2)|col between 1 and 2||
|isNull("col")|col is null||
|isNotNull("col")|col is not null||
|where("col = 1 or col = 2")|(col = 1 or col = 2) |If specified with more than one or other extraction conditions, it is combined with an AND operator|
|asc("col1", "col2")| order by col1 asc, col2 asc|Specify NULLS LAST if NULLS is available|
|asc("col1", Nulls.FIRST)| order by col1 asc NULLS FIRST|When specified more than once, they are arranged in call order|
|desc("col1", "col2")| order by col1 desc, col2 desc|Specify NULLS LAST if NULLS is available|
|desc("col1", Nulls.FIRST)| order by col1 desc NULLS FIRST|When specified more than once, they are arranged in call order|
|limit(10)|LIMIT 10|Throw UroborosqlRuntimeException if the limit database can not be used. The sentence to be output is switched depending on the dialect of the database.|
|offset(10)|OFFSET 10|Throw UroborosqlRuntimeException if the offset database can not be used. The sentence to be output is switched depending on the dialect of the database.|
