### ISSUE TITLE
Add SqlAgent#delete overload method

### ISSUE THREAD

**Issue by shout-star** [future-architect/uroborosql#158]
Currently, the `SqlAgent#delete method` is `int delete (Object entity)` and takes an entity class as an argument, but it seems that there may be an overloaded method which executes by passing only the primary key .

The signature you want to add is below.
```java
<E> int delete(Class<? extends E> entityType, Object... keys)
```

**Comment by HidekiSugimoto189** [comment]
fixed with #160
