### ISSUE TITLE
I would like SqlEntityQuery to add max, min, sum acquisition method.

### ISSUE THREAD

**Issue by snm2048** [future-architect/uroborosql#175]
Hi..

Thank you for adding count acquisition method in issue #164.

This time, please add a method to get the minimum value, maximum value and total value of the specified column when using SqlEntity.

Thanks.

**Comment by HidekiSugimoto189** [comment]
### Aggrigate functions
|DB|minimum|maximum|sum|count|
|:---|:---|:---|:---|:---|
|Oracle|MIN([DISTINCT/**ALL**] expr)|MAX([DISTINCT/**ALL**] expr)|SUM([DISTINCT/**ALL**] expr)|COUNT (*), COUNT([DISTINCT/**ALL**] expr)|
|Postgresql|min(expr)|max(expr)|sum(expr)|count(*), count(expr)|
|MySQL|MIN([DISTINCT] expr)|MAX([DISTINCT] expr)|SUM([DISTINCT] expr)|COUNT(expr), COUNT(DISTINCT expr, [expr...])|
|MSSQL|MIN([DISTINCT/**ALL**] expr)|MAX([DISTINCT/**ALL**] expr)|SUM([ALL|DISTINCT] expr)|COUNT (*), COUNT([DISTINCT/**ALL**] expr)|
|H2DB|min(expr)|max(expr)|sum([DISTINCT/**ALL**] expr)|count(*), count([DISTINCT/**ALL**] expr)|

**Comment by HidekiSugimoto189** [comment]
The DISTINCT option of SUM () and COUNT () will be supported in the future.
