### ISSUE TITLE
I want a Consumer to be called when the transaction ends

### ISSUE THREAD

**Issue by shout-star** [future-architect/uroborosql#230]
For example, I want to be able to register `Consumer` when initializing SqlConfig as below.
This is because the ability to hook commit / rollback allows you to insert common processing that you want to do only when the transaction succeeds.

```java
SqlConfig config = UroboroSQL.builder(...)
  .setSqlAgentFactory(new SqlAgentFactoryImpl()
    addPreCommitHook((ctx) -> this.something(ctx))
    addPreRollbackHook((ctx) -> this.something(ctx))
  )
).build();
```

**Comment by HidekiSugimoto189** [comment]
support with #311
