### ISSUE TITLE
 I want you to be able to do between in two columns

### ISSUE THREAD

**Issue by snmk2478** [future-architect/uroborosql#295]
Hi..

I want you to be able to perform between with two columns when using the DAO interface.

ex) `'20210331' between valid_at and invalid_at`

Thanks.

**Comment by HidekiSugimoto189** [comment]
Hi snmk2478.
Thanks for the Issue.

This is what I would do if I could achieve this with the current API.

```java
   agent().query(Entity.class)
       .where("/*between_date*/'20210331' between valid_at and invalid_at", Map.of("between_date", LocalDate.of(2021, 3, 31))
       .collect();
```

But it is not a smart way to write it, so I will add an API.

```java
   agent().query(Entity.class)
       .betweenColumns(LocalDate.of(2021, 3, 31), "valid_at", "invalid_at")
       .collect();
```
