### ISSUE TITLE
What is the best way to "SELECT COUNT(*)" with "SqlAgent#query" ?

### ISSUE THREAD

**Issue by cypher256** [future-architect/uroborosql#301]
Thank you for publishing this cool library.

Temurin-17.0.3+7 (build 17.0.3+7)
implementation 'jp.co.future:uroborosql:0.24.+'
implementation 'com.zaxxer:HikariCP:5.0.+'
runtimeOnly 'com.h2database:h2:2.1.+'

```java

String sql = "SELECT COUNT(*) FROM WHERE 〜";
agent.queryWith(sql).paramBean(paramBean).one(Integer.class);

java.lang.Integer.<init>()
java.lang.NoSuchMethodException: java.lang.Integer.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at jp.co.future.uroborosql.converter.EntityResultSetConverter.<init>(EntityResultSetConverter.java:55)
	at jp.co.future.uroborosql.SqlQueryImpl.stream(SqlQueryImpl.java:262)
	at jp.co.future.uroborosql.SqlQueryImpl.findOne(SqlQueryImpl.java:161)
	at jp.co.future.uroborosql.SqlQueryImpl.one(SqlQueryImpl.java:135)
```
---
```java
agent.queryWith(sql).paramBean(paramBean).one().values().iterator().next();
```

I can get it right above, but is there an easier way?
I believe the following method is performance problematic because it retrieves all the data.

```java
String sql2 = "SELECT id FROM WHERE 〜";
agent.queryWith(sql2).paramBean(paramBean).collect().size();
agent.queryWith(sql2).paramBean(paramBean).stream().count();
```

I know SqlEntityQuery#count, but I want to use SqlQuery.
#176 Add count() / sum() / min() / max() / exists() / notExists() to SqlEntityQuery

**Comment by HidekiSugimoto189** [comment]
@cypher256

Thanks for the question.

It's true that there is nothing in the current API to get the result of count directly. You can get it either by the method raised above or by writing the following.

```
var sql = "SELECT COUNT(*) AS CNT FROM WHERE 〜";
var count = agent.queryWith(sql).paramBean(paramBean).one().get("CNT");
```

I'll look into an API that makes it a little easier to get the result of a function.

**Comment by cypher256** [comment]
I will use "COUNT(*) AS CNT" for now.
Looking forward to the new API!

**Comment by HidekiSugimoto189** [comment]
@cypher256 

uroborosql v0.25.0 is released.

collect / first / findFirst / one / findOne / stream  methods allows you to retrieve a value by specifying the column type.

```java
String sql = "SELECT COUNT(*) FROM WHERE 〜";
Integer count = agent.queryWith(sql).paramBean(paramBean).one(Integer.class);
```

See below for details. 
https://future-architect.github.io/uroborosql-doc/basics/sql-file-api.html#%E3%83%AA%E3%82%B9%E3%83%88%E5%8F%96%E5%BE%97-sqlquery-collect

**Comment by cypher256** [comment]
Awesome!
I was able to use it without issue.
