### ISSUE TITLE
The return value of batch update is always "-2"

### ISSUE THREAD

**Issue by shun-chiba** [future-architect/uroborosql#69]
The number of returned array matches the execution number of SQL.
However, all contents are -2.

**Comment by HidekiSugimoto189** [comment]
Hi!

Probably I think that it is a case using OracleJDBC.
In Oracle JDBC, the return value of PreparedStatemnt # executeBatch () is always -2 (Statement.SUCCESS_NO_INFO).

see.
https://stackoverflow.com/questions/19022175/executebatch-method-return-array-of-value-2-in-java

If you want to retrieve the number of updates, please process the return value with SqlFilter.

```java
@Override
public int[] doBatch(final SqlContext sqlContext, final PreparedStatement preparedStatement,
		final int[] result) {
	int[] counts = result;
	try {
		counts = new int[] { preparedStatement.getUpdateCount() };
	} catch (SQLException ex) {
		ex.printStackTrace();
	}
	return counts;
}
```
